### PR TITLE
Rationalize sign conventions

### LINKED ISSUE #4: Figure out sign conventions
One of the current points of confusion is whether the coordinate system is y-up or y-down. The former is more conventional in math, the latter completely standard in graphics these days (though this was less true, PostScript was y-up, as are fonts to this day).

Related issues are conventions around whether a positive area shape is clockwise or withershins, and whether a clockwise circle has positive or negative signed curvature. The winding number should match area - it should be positive if the point is inside a positive area shape. Either convention will do, but it should be consistent.

Another thing that falls in the same category is the convention of `Vec2::cross`. The right hand rule says right ^ up = 1, but is up (0, 1) or (0, -1)? For this, I think we pick one and document it.

I do think kurbo is interesting in both math and graphics contexts. For methods like `Vec2::from_angle` and `Affine::rotate` it's hard to just pick a convention, so I'm inclined to split them into `_y_up` and `_y_down` variants, so that the user makes an explicit choice. For the signed area stuff, I'm not sure there's a strong convention; e^{iπt} is anticlockwise in a y-up coordinate space as t increases. Do people know of other conventions we can follow? Something along the lines of https://github.com/JuliaLang/julia/issues/8750 which surveys rounding conventions of many languages might be a model.

Tagging @behdad @jrus @pomax @nical @Connicpu @kvark as they might have horses in this race.

### PR DESCRIPTION
**Pull request by raphlinus**
Document sign conventions in Shape. Add tests to confirm this is
indeed the behavior. Fix broken cases. Some doc touchup.

Fixes #4

### CODE REVIEW

**Comment by behdad** [comment]
Anticlockwise -> counterclockwise? I never heard the former. Might be just me.

**Comment by cmyr** [comment]
... I'm trying to come up with some joke about RTL clocks but it's falling flat 😒

**Comment by raphlinus** [comment]
Just be thankful I didn't say "widdershins." But I can change it to "counter" if there's a consensus it's clearer.

**Comment by behdad** [comment]
> ... I'm trying to come up with some joke about RTL clocks but it's falling flat

It's a matter of time...

**Comment by jrus** [comment]
I like “anticlockwise” better than “counterclockwise”. I believe the former is more common in British than American English. But both are commonly used all over the place.

But also +1 for switching to “[sunwise](https://en.wikipedia.org/wiki/Sunwise)” and “[widdershins](https://en.wikipedia.org/wiki/Widdershins)” :P

**Comment by cmyr** [comment]
It hurts me that the companion to 'dextrogyre' isn't 'sinistegyre'.

**Comment by jrus** [comment]
http://argos.vu/wp-content/uploads/2016/05/1976_Laffoley_The-Levogyre.pdf

**Pull request merged**
