### PR TITLE
Add `CHANGELOG.md`

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Review by derekdreery — COMMENTED** [review]
If we are going to have a changelog (which I think is a good idea) we should have a note on the README.md asking contributors to add a note to the changelog as part of their PR.

**Review by derekdreery — APPROVED** [review]
We discussed in office hours and decided to have changelog, and that we are aiming to have it for all linebender projects.

**Review by xStrom — APPROVED** [review]
In the grander scheme of things we want to have even better changelogs and a whole workflow on how they get continuously maintained. However none of that needs to happen in this PR.

Thanks for taking this step and getting us going!

**Comment by waywardmonkeys** [comment]
@xStrom Should I rebase, squash or merge commit? :)

**Comment by derekdreery** [comment]
> @xStrom Should I rebase, squash or merge commit? :)

Good question - IIRC we talked about it and prefer squash commits, but I may be wrong. I don't think it matters too much.

**Comment by xStrom** [comment]
Squash, merge queues will arrive sometime in the future. 😆

**Pull request merged**
