### PR TITLE
Add serde support

### LINKED ISSUE #54: serde support?
Is there any specific consideration that this crate does not have conditional serde serialization support? by the way great work.

### PR DESCRIPTION
**Pull request by zimond**
This PR adds basic serde support under conditional cargo's `serde` feature, resolves #54

### CODE REVIEW

**Comment by cmyr** [comment]
Oops, sorry for missing this. I believe that this is resolved in #55, (@raphlinus can confirm) but thank you for the PR!

**Comment by zimond** [comment]
Glad it's added!

**Comment by raphlinus** [comment]
I somehow missed the fact that there were two separate PR's for this feature :). In any case, thanks for the contribution and glad this got sorted out.

**Comment by jneem** [comment]
Is this really resolved by #55? That seems to be only about serialization to/from svg paths; this is serde support in general (which I also happened to want today).

**Comment by cmyr** [comment]
Nope, that was an oversight. Would be happy to have optional serde support for core types.

**Comment by cmyr** [comment]
@jneem are you interested in preparing a PR? you could start from this but it's pretty out of date.

**Comment by jneem** [comment]
Sure, I can make a PR, but I'll probably just start over.

**Pull request closed without merging**
