### PR TITLE
Don't skip first dash in dash pattern

### PR DESCRIPTION
**Pull request by dominikh**
Before this change, the dash iterator's initial state (before accounting
for the dash offset) was "processing first dash, with remaining length
of zero", which would cause the iterator to immediately jump to the next
component in the dash pattern, effectively skipping the first dash and
starting with a gap.

### CODE REVIEW

**Comment by dominikh** [comment]
This change currently breaks for non-zero dash offsets

**Comment by waywardmonkeys** [comment]
@dominikh Could you please rebase this on top of current `main` to pick up the CI changes / updates? Thanks!

**Review by raphlinus — APPROVED** [review]
Yes, the logic was wrong and this seems to be a valid fix. Thanks!

Related to this is the report in [Dashed Line misbehaves when used with dash-offset](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/Dashed.20Line.20misbehaves.20when.20used.20with.20dash-offset). I think it's worth re-checking the behavior.

Reading https://github.com/GraphiteEditor/Graphite/pull/1875, which is the tracking issue where the Graphite behavior was reported, I *think* this takes care of the sign negation, but it's possible there's another issue. Please file another bug against either kurbo or Vello if so.

**Comment by Keavon** [comment]
Thanks for getting to this in your review queue!

Once this lands and it's pulled in by the latest Vello master commit, we can try it out in Graphite to confirm the behavior matches the SVG spec. I'll report back in that Zulip thread if it's working, or file an issue here again if it's not.

**Pull request merged**
